title: Researcher
url: "."
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Recherche"
   link: "/recherche/"
 - name: "Enseignement"
   link: "/enseignement/"
 - name: "Contact"
   link: "contact"
