title: Thibaut Le Gouic
url: "https://thibautlg.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"


footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Résumé"
   link: "cv.pdf"
 - name: "Links"
   link: "links"
 - name: "Contact"
   link: "contact"
